### PR TITLE
Results screen lines fix

### PR DESCRIPTION
**Pull request by zhandrew4**
Copied Juan's branch for [results-screen-lines](https://github.com/Zinc42/-JIC-2118-Distal-Radius-Fracture-Analysis/pull/58/commits) over to a previous version to fix build errors on Android.

### CODE REVIEW

**Comment by zhandrew4** [comment]
@jperez01 Just be sure to commit the changes I commented on your other branches to here, and merge this branch instead of the original results-screen-lines branch.

**Review by jperez01 — APPROVED** [review]
Added the code necessary to fix certain issues, everything else LGTM

**Review by zhandrew4 — COMMENTED** [review]
Everything looks good.

**Comment by zhandrew4** [comment]
Fixed merge conflicts that arose after merging earlier branches

**Pull request merged**
