### PR TITLE
added initial screen layout

### PR DESCRIPTION
**Pull request by zhandrew4**
Just added basic UI elements for the menu screen and linked it to the current image upload screen.

Not yet set up to receive images back from the image crop/align screen.

### CODE REVIEW

**Review by jperez01 — APPROVED** [review]
LGTM

You had great use of error checking when things become null and also handling them, so you should continue that.

**Comment by zhandrew4** [comment]
Rebased onto the updated main branch.

**Comment by zhandrew4** [comment]
Rebased onto the updated main branch

**Comment by darienr1999** [comment]
Looks good to me

**Review by darienr1999 — APPROVED** [review]
Looks good to me. Code is clean and simple

**Pull request merged**
