### PR TITLE
add alignment line and input for scale length

### PR DESCRIPTION
**Pull request by zhandrew4**
Added a red vertical line on the alignment confirm screen, in addition to an input for users to input the actual measured length of the line. 

The lengths of the line in px (on screen) and in cm (IRL) are stored in the Image Handler.

### CODE REVIEW

**Comment by jperez01** [comment]
I checked it on iOS, and it works fine.

**Review by darienr1999 — APPROVED** [review]
Looks good to me

**Review by jperez01 — APPROVED** [review]
LGTM

**Comment by zhandrew4** [comment]
I pulled updated changes from main, and added:

updated the image confirm screen so that the alignment scale input only shows for the frontal image, where it is needed.
fixed sizing inconsistencies across the alignment, results, and drag screens
fixed offset/alignment issues in drag screen (now the math is consistent and accurate)

**Comment by jperez01** [comment]
Just checked and it works on ios

**Review by jperez01 — APPROVED** [review]
LGTM

**Pull request merged**
